[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push --skip-generate && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.nixpacks]
pkgManager = "npm"
