[build]
builder = "nixpacks"
buildCommand = "cd apps/web && npm install && npx prisma generate && npx prisma db push && npm run build"
watchPatterns = ["apps/web/**"]

[deploy]
startCommand = "cd apps/web && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.nixpacks]
pkgManager = "npm"
aptPkgs = ["ffmpeg"]
